# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=4000

# ===============================
# CONEXIÓN A NEON POSTGRESQL (NUBE)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-small-night-an84r9ch-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GNxOJY3LH6fE

# ===============================
# CONFIGURACIÓN DE HIBERNATE (ORM)
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true