# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
# Cambiamos el puerto para que no choque con nada más
server.port=4000

# ===============================
# CONEXIÓN A POSTGRESQL
# ===============================

# ===============================
# CONEXIÓN A NEON POSTGRESQL (NUBE)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-small-night-an84r9ch-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_GNxOJY3LH6fE

# Cambia 'marakame_db' por el nombre real de tu base de datos
#spring.datasource.url=jdbc:postgresql://localhost:5432/marakame_db
#spring.datasource.username=postgres
# Pon aquí la contraseña con la que entras a tu pgAdmin
#spring.datasource.password=12345
# ===============================
# CONFIGURACIÓN DE HIBERNATE (ORM)
# ===============================
# 'update' hace que Spring Boot cree las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Esto te mostrará en la terminal los comandos SQL que se ejecutan por debajo
spring.jpa.show-sql=true